services:
  - type: web
    name: telegram-sms-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: RENDER
        value: true
      - key: WEBHOOK_URL
        fromService:
          name: telegram-sms-bot
          type: web
          property: url